# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobufs import recipe_recommendation_pb2 as recipe__recommendation__pb2

class RecipeRecommendationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllRecipes = channel.unary_unary(
                '/RecipeRecommendationGRPC.RecipeRecommendation/GetAllRecipes',
                request_serializer=recipe__recommendation__pb2.GetAllRecipesRequest.SerializeToString,
                response_deserializer=recipe__recommendation__pb2.GetAllRecipesResponse.FromString,
                )
        self.UpdateRecipe = channel.unary_unary(
                '/RecipeRecommendationGRPC.RecipeRecommendation/UpdateRecipe',
                request_serializer=recipe__recommendation__pb2.UpdateRecipeRequest.SerializeToString,
                response_deserializer=recipe__recommendation__pb2.UpdateRecipeResponse.FromString,
                )
        self.DeleteRecipe = channel.unary_unary(
                '/RecipeRecommendationGRPC.RecipeRecommendation/DeleteRecipe',
                request_serializer=recipe__recommendation__pb2.DeleteRecipeRequest.SerializeToString,
                response_deserializer=recipe__recommendation__pb2.DeleteRecipeResponse.FromString,
                )
        self.CreateRecipe = channel.unary_unary(
                '/RecipeRecommendationGRPC.RecipeRecommendation/CreateRecipe',
                request_serializer=recipe__recommendation__pb2.CreateRecipeRequest.SerializeToString,
                response_deserializer=recipe__recommendation__pb2.CreateRecipeResponse.FromString,
                )


class RecipeRecommendationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllRecipes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecipeRecommendationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllRecipes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllRecipes,
                    request_deserializer=recipe__recommendation__pb2.GetAllRecipesRequest.FromString,
                    response_serializer=recipe__recommendation__pb2.GetAllRecipesResponse.SerializeToString,
            ),
            'UpdateRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecipe,
                    request_deserializer=recipe__recommendation__pb2.UpdateRecipeRequest.FromString,
                    response_serializer=recipe__recommendation__pb2.UpdateRecipeResponse.SerializeToString,
            ),
            'DeleteRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecipe,
                    request_deserializer=recipe__recommendation__pb2.DeleteRecipeRequest.FromString,
                    response_serializer=recipe__recommendation__pb2.DeleteRecipeResponse.SerializeToString,
            ),
            'CreateRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecipe,
                    request_deserializer=recipe__recommendation__pb2.CreateRecipeRequest.FromString,
                    response_serializer=recipe__recommendation__pb2.CreateRecipeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RecipeRecommendationGRPC.RecipeRecommendation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecipeRecommendation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllRecipes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecipeRecommendationGRPC.RecipeRecommendation/GetAllRecipes',
            recipe__recommendation__pb2.GetAllRecipesRequest.SerializeToString,
            recipe__recommendation__pb2.GetAllRecipesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecipeRecommendationGRPC.RecipeRecommendation/UpdateRecipe',
            recipe__recommendation__pb2.UpdateRecipeRequest.SerializeToString,
            recipe__recommendation__pb2.UpdateRecipeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecipeRecommendationGRPC.RecipeRecommendation/DeleteRecipe',
            recipe__recommendation__pb2.DeleteRecipeRequest.SerializeToString,
            recipe__recommendation__pb2.DeleteRecipeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecipeRecommendationGRPC.RecipeRecommendation/CreateRecipe',
            recipe__recommendation__pb2.CreateRecipeRequest.SerializeToString,
            recipe__recommendation__pb2.CreateRecipeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
